import { useState } from 'react';
import { TaskGroup } from '../utils/types';

export function useDashboardData() {
   const [taskGroups] = useState<TaskGroup[]>([
      {
         id: '1',
         title: 'In Progress',
         color: 'bg-yellow-400',
         tasks: [
            {
               id: '1-1',
               english: 'Which number do you want to buy on',
               isChecked: false,
               lrl: 'Number bɛn na wo pɛse wo tɔ gu su',
               assignees: ['AB', 'CD', 'EF'],
               dueDate: 'February 12, 2024',
               priority: 'Urgent',
               progress: 85,
               subtasks: 3,
               completedSubtasks: 3,
            },
            {
               id: '1-2',
               english: 'The father will sell his farm to earn money to buy a car',
               isChecked: true,
               lrl: "Papa no bɛtɔn n'afuo anya sika atɔ kaa",
               assignees: ['AB', 'CD'],
               dueDate: 'February 12, 2024',
               priority: 'Urgent',
               progress: 95,
            },
            {
               id: '1-3',
               english: 'The beautiful black dress is mine',
               isChecked: true,
               lrl: 'Ataadeɛ tuntum fɛɛfɛ no yɛ me dea',
               assignees: ['AB', 'CD', 'EF'],
               dueDate: 'February 12, 2024',
               priority: 'Urgent',
               progress: 100,
            },
            {
               id: '1-4',
               english:
                  'He has leaned against the curtains but the flies have moved causing the curtains to tear',
               isChecked: false,
               lrl: 'Wato ne ho ato curtains no so nanso nwansena no atu ama curtains no atete',
               assignees: ['AB', 'CD'],
               dueDate: 'February 12, 2024',
               priority: 'Normal',
               progress: 34,
            },
            {
               id: '1-5',
               english: 'The children are playing in the garden',
               isChecked: false,
               lrl: 'Mmofra no regoro wɔ turo no mu',
               assignees: ['GH', 'IJ'],
               dueDate: 'February 15, 2024',
               priority: 'Low',
               progress: 20,
            },
            {
               id: '1-6',
               english: 'My grandmother cooks delicious food',
               isChecked: true,
               lrl: 'Me nana baa noa aduane a ɛyɛ dɛ',
               assignees: ['AB', 'GH'],
               dueDate: 'February 18, 2024',
               priority: 'Normal',
               progress: 75,
            },
            {
               id: '1-7',
               english: 'The market opens early in the morning',
               isChecked: false,
               lrl: 'Gua no bue anɔpa tutuutu',
               assignees: ['CD', 'EF'],
               dueDate: 'February 20, 2024',
               priority: 'Urgent',
               progress: 45,
            },
            {
               id: '1-8',
               english: 'She is washing clothes by the river',
               isChecked: true,
               lrl: 'Ɔrehorɔ ntaadeɛ wɔ asubɔnten no ho',
               assignees: ['IJ', 'KL'],
               dueDate: 'February 22, 2024',
               priority: 'Normal',
               progress: 60,
            },
            {
               id: '1-9',
               english: 'The sun sets in the west',
               isChecked: false,
               lrl: 'Owia no kɔtɔ atɔeɛ',
               assignees: ['AB'],
               dueDate: 'February 24, 2024',
               priority: 'Low',
               progress: 15,
            },
            {
               id: '1-10',
               english: 'The farmer planted maize last season',
               isChecked: true,
               lrl: 'Kuafo no duaa aburoɔ berɛ a atwam no',
               assignees: ['CD', 'GH'],
               dueDate: 'February 26, 2024',
               priority: 'Normal',
               progress: 90,
            },
            {
               id: '1-11',
               english: 'My brother is a teacher at the local school',
               isChecked: false,
               lrl: 'Me nua barima yɛ kyerɛkyerɛfoɔ wɔ manɔɔ sukuu no',
               assignees: ['EF', 'IJ'],
               dueDate: 'February 28, 2024',
               priority: 'Urgent',
               progress: 50,
            },
            {
               id: '1-12',
               english: 'The chief called a meeting of the elders',
               isChecked: true,
               lrl: 'Ɔhene no frɛɛ mpanimfoɔ nhyiamu',
               assignees: ['AB', 'KL'],
               dueDate: 'March 2, 2024',
               priority: 'Urgent',
               progress: 80,
            },
            {
               id: '1-13',
               english: 'The rain has been falling since morning',
               isChecked: false,
               lrl: 'Osu atɔ firi anɔpa',
               assignees: ['CD', 'GH'],
               dueDate: 'March 4, 2024',
               priority: 'Normal',
               progress: 30,
            },
            {
               id: '1-14',
               english: 'She bought new shoes at the mall',
               isChecked: true,
               lrl: 'Ɔtɔɔ mpaboa foforɔ wɔ dwɛtire no',
               assignees: ['EF', 'IJ'],
               dueDate: 'March 6, 2024',
               priority: 'Low',
               progress: 65,
            },
            {
               id: '1-15',
               english: 'The bird built a nest on the tree',
               isChecked: false,
               lrl: 'Anomaa no yɛɛ berebuw wɔ dua no so',
               assignees: ['AB', 'CD'],
               dueDate: 'March 8, 2024',
               priority: 'Normal',
               progress: 40,
            },
            {
               id: '1-16',
               english: 'We will celebrate the festival next week',
               isChecked: true,
               lrl: 'Yɛbɛdi afahyɛ no nawɔtwe a ɛreba no',
               assignees: ['GH', 'KL'],
               dueDate: 'March 10, 2024',
               priority: 'Urgent',
               progress: 70,
            },
            {
               id: '1-17',
               english: 'The doctor gave me medicine for my headache',
               isChecked: false,
               lrl: 'Dɔkota no maa me aduro maa me tirim yaw',
               assignees: ['EF', 'IJ'],
               dueDate: 'March 12, 2024',
               priority: 'Urgent',
               progress: 25,
            },
            {
               id: '1-18',
               english: 'The students are taking their final exams',
               isChecked: true,
               lrl: 'Asuafoɔ no reyɛ wɔn awiee nsɔhwɛ',
               assignees: ['AB', 'CD'],
               dueDate: 'March 14, 2024',
               priority: 'Normal',
               progress: 85,
            },
            {
               id: '1-19',
               english: 'My uncle will visit us during the holidays',
               isChecked: false,
               lrl: 'Me wɔfa bɛba abɛsra yɛn ahomegyeɛ berɛ no',
               assignees: ['GH', 'KL'],
               dueDate: 'March 16, 2024',
               priority: 'Low',
               progress: 10,
            },
            {
               id: '1-20',
               english: 'The moon shines brightly at night',
               isChecked: true,
               lrl: 'Bosome no hyerɛn kuturuku anadwo',
               assignees: ['EF', 'IJ'],
               dueDate: 'March 18, 2024',
               priority: 'Normal',
               progress: 55,
            },
         ],
      },
   ]);
   const [activeTab, setActiveTab] = useState('spreadsheet');

   return {
      taskGroups,
      activeTab,
      setActiveTab,
   };
}
